baseURL = "https://maxime-cls.github.io/kubernetes-tutorial/"
languageName = "Français"
languageCode = "fr-FR"
title = "Kubernetes Tutoriel"
theme = "hugo-theme-learn"

[params]
themeVariant = "blue"
author = "Maxime Calves"
description = "Tutoriel sur Kubernetes"
showVisitedLinks = true
disableSearch = false


[outputs]
home = ["HTML", "RSS", "JSON"]